### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by LRF520** [snip3rnick/PyHardwareMonitor#1]
How to use ?

**Comment by snip3rnick** [comment]
Hi,
I just threw this together for using it in a project some time in the future and did not expect anyone to use this so soon.
When I find the time in the coming days I will add a proper README with references and example use.
For now I can refer you to the [*testing example*](../blob/main/test/TestHardwareMonitor.py) which is the equivalent replica of the [**C#** example in LibreHardwareMonitor repository](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor#whats-the-easiest-way-to-start).

But I will definitely get back to you once the installation and usage instructions are added ;).

Cheers

**Comment by LRF520** [comment]
> 嗨， 我只是把它放在一起，以便将来在某个项目中使用它，没想到有人这么快就使用它。 当我在接下来的几天里找到时间时，我将添加一个适当的 README，其中包含参考和示例使用。 现在我可以参考[_测试示例_](../blob/main/test/TestHardwareMonitor.py)[，它是LibreHardwareMonitor 存储库中](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor#whats-the-easiest-way-to-start)[**C#**](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor#whats-the-easiest-way-to-start)示例的等效副本。
> 
> 但是，一旦添加了安装和使用说明，我一定会回复您；）。
> 
> 干杯


Librehardware monitor provides a way to obtain JSON data. If pyhardwardware monitor can also provide such JSON data or dict data in the future, it is very good because it is convenient to use. It does not need to run the GUI interface of librehardware monitor because it consumes too much CPU.

I have studied pyhardwaremonitor for two days. If you can continue to do it, I think this scheme is very good.


![image](https://user-images.githubusercontent.com/58470642/187819596-d8539731-dbe3-4abd-b0d0-f1bcd84239d5.png)

**Comment by snip3rnick** [comment]
It would not be very difficult to write a utility for json serialization for the LibreHardwareMonitor objects.
I can certainly look into that this coming weekend.
The server made with pythons standard library may look as simple as this
```python
from wsgiref import simple_server

def app(environ, respond):
    if environ['PATH_INFO'].lower() == "/data.json":
        json_str = '{}'  # TODO: insert PyHardwareMonitor serialization here
        respond('200 OK', [('Content-Type', 'application/json')])
        return [json_str.encode()]
    else:
        respond('404 Not Found', [('Content-Type', 'application/json')])
        return [b'not found']

httpd = simple_server.make_server('', 8085, app)
print(f"Serving on port {httpd.server_port}, press 'ctrl + C' to stop")
try:
    httpd.serve_forever()
except KeyboardInterrupt:
    httpd.server_close()
```

**Comment by snip3rnick** [comment]
I have updated some files and added a more useful README which should help with using this package.
An example script for a webserver based sensor data provider will be added shortly.

Cheers

**Comment by snip3rnick** [comment]
The [WSGI example sensor provider](https://github.com/snip3rnick/PyHardwareMonitor/blob/main/examples/wsgi_provider.py) is now uploaded.  
This script runs a background timer to update the sensor values and sends the entire data as JSON string when accessing [localhost:8085/data.json](http://localhost:8085/data.json).

Remember that LibreHardwareMonitor requires admin privileges for most sensors to properly readout values.

> NOTE: Fields in the JSON are currently the names of the .NET object members and not generalized like LibreHardwareMonitor does.

**Comment by LRF520** [comment]
> [WSGI 示例传感器提供程序](https://github.com/snip3rnick/PyHardwareMonitor/blob/main/examples/wsgi_provider.py)现已上传。[此脚本运行后台计时器以更新传感器值，并在访问localhost:8085/data.json](http://localhost:8085/data.json) 时将整个数据作为 JSON 字符串发送。[](http://localhost:8085/data.json)
> 
> 请记住，LibreHardwareMonitor 需要管理员权限才能让大多数传感器正确读取值。
> 
> > 注意：JSON 中的字段当前是 .NET 对象成员的名称，不像 LibreHardwareMonitor 那样通用。


Still unavailable


![image](https://user-images.githubusercontent.com/58470642/188781819-2c6f20b6-a071-455c-9ed1-7c0ba627b6d5.png)

**Comment by snip3rnick** [comment]
comment redundant to issue #2
