### ISSUE TITLE
Still unavailable

### ISSUE THREAD

**Issue by LRF520** [snip3rnick/PyHardwareMonitor#2]
Still unavailable

![image](https://user-images.githubusercontent.com/58470642/188781819-2c6f20b6-a071-455c-9ed1-7c0ba627b6d5.png)

**Comment by snip3rnick** [comment]
This is apparently a problem with older installations. I did not encounter this on both my main computers running Python 3.9 and 3.10 respectively.  
On another machine I did in fact replicate this problem with Python 3.7.

The solution was added with commit c9ebd6b and 6e6ae8c.

**Comment by LRF520** [comment]
> This is apparently a problem with older installations. I did not encounter this on both my main computers running Python 3.9 and 3.10 respectively. On another machine I did in fact replicate this problem with Python 3.7.
> 
> The solution was added with commit [c9ebd6b](https://github.com/snip3rnick/PyHardwareMonitor/commit/c9ebd6bf907ed64226d4d173dcd6467e07e37d1e) and [6e6ae8c](https://github.com/snip3rnick/PyHardwareMonitor/commit/6e6ae8c2da6c295a9e1200cc5364d7d9cc70de2a).

Still errors~~~

![image](https://user-images.githubusercontent.com/58470642/188892076-87edc4f4-f8cb-46d7-908e-a86b46350731.png)
```sh
Loading devices and sensors...
Traceback (most recent call last):
  File "D:/pythonBF/demo/PyHardware.py", line 71, in <module>
    main()
  File "D:/pythonBF/demo/PyHardware.py", line 63, in main
    app = SensorApp()
  File "D:/pythonBF/demo/PyHardware.py", line 28, in __init__
    self.computer = OpenComputer(all=True, time_window=interval)
  File "C:\Program Files\Python37\lib\site-packages\HardwareMonitor\Util.py", line 81, in OpenComputer
    return computer.Update()
  File "C:\Program Files\Python37\lib\site-packages\HardwareMonitor\Util.py", line 63, in Update
    self.Accept(self._visitor)
System.OverflowException: Negating the minimum value of a twos complement number is invalid.
   at System.Math.AbsHelper(Int32 value)
   at LibreHardwareMonitor.Hardware.Battery.Battery.Update()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyObject[] args)
   at Python.Runtime.PythonDerivedType.InvokeMethodVoid(IPythonDerivedType obj, String methodName, String origMethodName, Object[] args, RuntimeMethodHandle methodHandle)
   at HardwareMonitor.Util.UpdateVisitor.VisitHardware(IHardware )
   at LibreHardwareMonitor.Hardware.Computer.Traverse(IVisitor visitor)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyObject[] args)
   at Python.Runtime.PythonDerivedType.InvokeMethodVoid(IPythonDerivedType obj, String methodName, String origMethodName, Object[] args, RuntimeMethodHandle methodHandle)
   at HardwareMonitor.Util.UpdateVisitor.VisitComputer(IComputer )

Process finished with exit code 1
```

**Comment by snip3rnick** [comment]
Apparently there is an issue in the *LibreHardwareMonitorLib* with value calculations.  
I will not be able to resolve or mitigate this behavior by myself as I can't reproduce this on any machine.

My immediate suggestion would be catching any exceptions in the `HardwareMonitor.Util.UpdateVisitor.VisitHardware` method.  
The calls to `ISensor.Update()` could be encapsulated in a `try`-`except` block ignoring exceptions for now.

```python
class UpdateVisitor(IVisitor):
    ...
    def VisitHardware(self, hardware: IHardware):
        try:    hardware.Update()
        except: pass
        for subHardware in hardware.SubHardware:
            try:    subHardware.Update()
            except: pass
    ...
```
This might prevent crashing at the sensor update stage but will of course lead to false data for sensors that keep failing to update properly.

**Comment by snip3rnick** [comment]
For future reference, please format stack traces as monospace block for readability.  
If possible please also translate crucial information to English.

Thanks in advance ;)

**Comment by LRF520** [comment]
> For future reference, please format stack traces as monospace block for readability. If possible please also translate crucial information to English.
> 
> Thanks in advance ;)

I'm here again. I want to feed back two questions:


(1) According to your guidance, I received json data, but I'm not sure whether this data is correct. After all, we used try... Except, the error is ignored:

![20220908_144738](https://user-images.githubusercontent.com/58470642/189055181-e3996316-05ff-416e-a602-ad2cfdc7eb8b.jpg)

(2) When I run the testhardwaremonitor.py code, it seems that there are similar errors:

![20220908_144948](https://user-images.githubusercontent.com/58470642/189055305-8faa3683-8811-4559-86cd-61ab91332699.jpg)

Traceback (most recent call last):
  File "D:/DATA/pythonBF/demo/PyHardware.py", line 29, in <module>
    computer.Accept(UpdateVisitor())
  File "D:/DATA/pythonBF/demo/PyHardware.py", line 6, in VisitComputer
    computer.Traverse(self);
  File "D:/DATA/pythonBF/demo/PyHardware.py", line 9, in VisitHardware
    hardware.Update()
System.OverflowException: The operation of negating the minimum value of the complement of 2 is invalid.
 in System.Math.AbsHelper(Int32 value)
 in LibreHardwareMonitor.Hardware.Battery.Battery.Update()

**Comment by snip3rnick** [comment]
Firstly thanks for translating the output for me, that is much appreciated.  
To your questions:
- **(1)** The sensor data should be correct except for your battery readout (since it usually crashed there).
  Updated are deterministic and in order with the battery component being the last one to update.
  That means all other sensors were updated without a problem.  
  You may not be running the script with **admin privileges**, which is needed even for measurements like the CPU frequencies. I have not mentioned that in the readme, but I realize that the requirement may not be common knowledge.
  
  The json output is not formatted in the same way the as LibreHardwareMonitor GUI sends it. Currently this script just serializes the object tree of `Hardware`, `Sensor`, ... instances keeping the structure and member names as is.  
  With a bit of extra coding the output can easily be made equal to the aforementioned GUI.
  
- **(2)** This was my first test script which has its own implementation of the `IVisitor` interface.  
  The `ISensor.Update()` would require the same encapsulation to work on your computer.
  
---
I might add the `try`-`except` "solution" to the module, them with emitting a warning once if the update failed.  
Secondly, I can add a check for admin privileges within the module. Emitting a warning could be helpful.

Cheers

**Comment by LRF520** [comment]
> Firstly thanks for translating the output for me, that much appreciated. To your questions:
> 
> * **(1)** The sensor data should be correct except for your battery readout (since it usually crashed there).
>   Updated are deterministic and in order with the battery component being the last one to update.
>   That means all other sensors were updated without a problem.
>   You may not be running the script with **admin privileges**, which is needed even for measurements like the CPU frequencies. I have not mentioned that in the readme, but I realize that the requirement may not be common knowledge.
>   The json output is not formatted in the same way the as LibreHardwareMonitor GUI sends it. Currently this script just serializes the object tree of `Hardware`, `Sensor`, ... instances keeping the structure and member names as is.
>   With a bit of extra coding the output can easily be made equal to the aforementioned GUI.
> * **(2)** This was my first test script which has its own implementation of the `IVisitor` interface.
>   The `ISensor.Update()` would require the same encapsulation to work on your computer.
> 
> I might add the `try`-`except` "solution" to the module, them with emitting a warning once if the update failed. Secondly, I can add a check for admin privileges within the module. Emitting a warning could be helpful.
> 
> Cheers

I used to use the JSON data of librehardwaremonitor GUI before. If the JSON data of pyhardwaremonitor keeps the same format as the JSON data of librehardwaremonitor GUI, it would be great. In this way, I don't have to modify the request code of JSON data again. I'm not as powerful as you!

In fact, I have started the python file with administrator privileges, but if I do not use try, except, the error will still appear.

![image](https://user-images.githubusercontent.com/58470642/189081663-bb44cd05-70cf-4c37-bbe6-4fe7f8c2444a.png)

**Comment by snip3rnick** [comment]
Since the original problem is resolved I have moved the requests into appropriate issues #3 and #4
