### ISSUE TITLE
Build PIP package ?

### ISSUE THREAD

**Issue by benoit-cty** [snip3rnick/PyHardwareMonitor#6]
Hello, I find your package while looking for an alternative to Intel Power Gadget for CodeCarbon : https://github.com/mlco2/codecarbon/issues/457

We would like to use your library to monitor power usage in Watt of Windows computers.

I could help you to publish your package to Pypi if you want to do so. We need this to import your package. I dont' think we could include your source code as we do not have the same licence.

![348363864-d332158e-6e43-43ba-b1b8-01d5452345c1](https://github.com/user-attachments/assets/de0ffce9-48ec-4e0e-8178-16825c975d14)

**Comment by snip3rnick** [comment]
Hello, please excuse me responding late.

I am not opposed to making the package ready for publishing to pypi, we can certainly look into making that happen.
When it comes to licensing, I am not and will not impose any prohibitive license onto the code.  
This is just a shallow layer for the LibreHardwareMonitorLib, which implies that the license for that library has to comply with your application.  
They are using the [**Mozilla Public License 2.0**](https://github.com//LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LICENSE), which as I see it requires subjecting derivative software to the same license.  
To my knowledge this does not apply to use of built software based on publicly available code bases, which is true in this case.

**Comment by snip3rnick** [comment]
I had forgotten about this matter but finally came around to setting up the workflows for publishing.

**Comment by benoit-cty** [comment]
Nice, thanks for that :+1:
